### ISSUE TITLE
Update image more frequently in pipeline; workstations weekly or on-demand

### ISSUE THREAD

**Issue by mcwumbly** [XanderStrike/devenv#5]
I think we could improve the pipeline by making the following changes:

1. Add a trigger to the `devenv` resource in the `build-canary-vm` job so it triggers on changes to the repo and publishes a new image
2. Remove the time-based trigger on the `build-canary-vm` job
3. Remove the image-based triggers on the other `workstation` jobs
4. Add time-based triggers to all workstation jobs.
5. Add a `destroy-canary-vm` job that triggers after a successful `build-canary-vm`

This would make it so that:

1. The image is updated any time there is a change to this repo
2. Workstations an be re-deployed any time by manual trigger with that image which is closer to being in sync w/ the repo
3. The canary vm would exist only for test purposes (but the destroy job could be paused if it needs inspection)

Thoughts?

**Comment by XanderStrike** [comment]
I'm gonna work on this today!

**Comment by XanderStrike** [comment]
All done! The image now gets rebuilt on pushes to this repo, and the workstations are rolled Saturdays or whenever they're triggered manually.

For now I've made the "canary" vm just one of the workstation VMs since folks were working on it today, but once I'm back on cf-for-k8s next week we'll figure something out for that.
